### ISSUE TITLE
Criteria for Inclusion +  Criteria for Exclusion or Objection

### ISSUE THREAD

**Issue by marcoscaceres** [a11y-api/a11y-api#33] opened 2016-08-11 07:06 UTC
These sections should be moved to a CONTRIBUTING.md file - they will eventually need to be removed from the spec. We can just point people to the CONTRIBUTING file.

**Comment by domenic** [comment] 2016-08-11 13:43
Dupe of #17

**Closed** 2016-08-12 07:42 UTC
